name: Automacao ApVerify

on:
  push:
    branches:
      - master  # ajuste conforme sua branch principal
  schedule:
    - cron: '*/2 * * * *'  # Executa a cada dois minutos
# on:
#   schedule:
#     - cron: '*/2 * * * *'  # Executa a cada dois minutos
#     # - cron: '0 9,14,19 * * *'  # Executa às 9:00, 14:00 e 19:00 (horário local)
    
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifique a versão do Python que você está usando

      - name: Install dependencies
        run:
          pip install selenium
          pip install beautifulsoup4

      # - name: Instalar o driver do Firefox (geckodriver)
      #   run:
      #     wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
      #     tar -xzf geckodriver-v0.30.0-linux64.tar.gz
      #     sudo mv geckodriver /usr/local/bin/
      #     sudo chmod +x /usr/local/bin/geckodriver    

      - name: Install Chrome WebDriver
        run: |
          LATEST=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver


      - name: Run Python script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python3 apInfo.py